//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use sea_orm::sea_query::IntoCondition;
use sea_orm::{JoinType, QuerySelect};
use serde::{Deserialize, Serialize};

use crate::permissions;
use crate::permissions::find_all_by_user_id;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub iban: Option<String>,
    pub balance: i64,
    pub original_balance: i64,
    pub currency: i64,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::currency::Entity",
        from = "Column::Currency",
        to = "super::currency::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Currency,
}

impl Related<super::currency::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Currency.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

find_all_by_user_id!(Entity);

impl Entity {
    pub fn find_by_id_and_user_id(id: i64, user_id: i64) -> Select<Self> {
        Self::find()
            .join_rev(
                JoinType::InnerJoin,
                permissions::Entity::belongs_to(Self)
                    .from(permissions::Column::EntityId)
                    .to(Column::Id)
                    .on_condition(|_left, _right| {
                        Expr::col(permissions::Column::EntityType).eq(Self.table_name()).into_condition()
                    })
                    .into(),
            )
            .filter(permissions::Column::UserId.eq(user_id))
            .filter(Column::Id.eq(id))
    }
}
