//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use sea_orm::sea_query::IntoCondition;
use sea_orm::ActiveValue::Set;
use sea_orm::{JoinType, Order, QueryOrder, QuerySelect};

use crate::entity::db_model::permissions;
use crate::entity::db_model::permissions::find_all_by_user_id;
use utility::snowflake::entity::Snowflake;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account")]
pub(crate) struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub(crate) id: i64,
    #[sea_orm(column_type = "Text")]
    pub(crate) name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub(crate) description: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub(crate) iban: Option<String>,
    pub(crate) balance: i64,
    pub(crate) original_balance: i64,
    pub(crate) currency: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub(crate) enum Relation {
    #[sea_orm(
        belongs_to = "super::currency::Entity",
        from = "Column::Currency",
        to = "super::currency::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Currency,
}

impl Related<super::currency::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Currency.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

find_all_by_user_id!(Entity);

impl Entity {
    pub(crate) fn find_by_id_and_user_id(id: Snowflake, user_id: Snowflake) -> Select<Self> {
        Self::find()
            .join_rev(
                JoinType::InnerJoin,
                permissions::Entity::belongs_to(Self)
                    .from(permissions::Column::EntityId)
                    .to(Column::Id)
                    .on_condition(|_left, _right| {
                        Expr::col(permissions::Column::EntityType).eq(Self.table_name()).into_condition()
                    })
                    .into(),
            )
            .filter(permissions::Column::UserId.eq(user_id))
            .filter(Column::Id.eq(id))
            .order_by(Column::Id, Order::Desc)
    }
}

impl ActiveModel {
    pub(crate) fn new(
        snowflake: Snowflake,
        name: &str,
        description: &Option<String>,
        iban: &Option<String>,
        balance: i64,
        currency_id: Snowflake,
    ) -> Self {
        Self {
            id: Set(snowflake.id),
            name: Set(name.to_string()),
            description: Set(description.to_owned()),
            iban: Set(iban.to_owned()),
            balance: Set(balance.to_owned()),
            original_balance: Set(balance),
            currency: Set(currency_id.id),
        }
    }
}
