//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use crate::snowflake::snowflake_type::Snowflake;
use sea_orm::entity::prelude::*;
use sea_orm::{Order, QueryOrder};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "budget")]
pub(crate) struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub(crate) id: i64,
    pub(crate) user: i64,
    pub(crate) amount: i64,
    #[sea_orm(column_type = "Text")]
    pub(crate) name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub(crate) description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub(crate) enum Relation {
    #[sea_orm(has_many = "super::transaction::Entity")]
    Transaction,
    #[sea_orm(has_many = "super::transaction_template::Entity")]
    TransactionTemplate,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::User",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl Related<super::transaction_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionTemplate.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Entity {
    pub(crate) fn find_all_by_user_id(user_id: Snowflake) -> Select<Self> {
        Self::find().filter(Column::User.eq(user_id)).order_by(Column::Id, Order::Desc)
    }
}
