//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "currency_conversion_rate")]
pub(crate) struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub(crate) source_currency: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub(crate) target_currency: i64,
    pub(crate) conversion_rate: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub(crate) enum Relation {
    #[sea_orm(
        belongs_to = "super::currency::Entity",
        from = "Column::SourceCurrency",
        to = "super::currency::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Currency2,
    #[sea_orm(
        belongs_to = "super::currency::Entity",
        from = "Column::TargetCurrency",
        to = "super::currency::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Currency1,
}

impl ActiveModelBehavior for ActiveModel {}
