//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub(crate) mod account;
pub(crate) mod budget;
pub(crate) mod currency;
pub(crate) mod currency_conversion_rate;
pub(crate) mod permissions;
pub(crate) mod recurring_transaction;
pub(crate) mod session;
pub(crate) mod transaction;
pub(crate) mod transaction_template;
pub(crate) mod user;
