name: Create and publish Docker nightly-image

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'backend/**'
      - 'frontend/**'

concurrency:
  group: "docker-build"
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        config:
          - { working_directory: './backend', dockerfile: './backend/docker/rust/Dockerfile', image_name: 'financrr/backend' }
          - { working_directory: './frontend', dockerfile: './frontend/docker/Dockerfile', image_name: 'financrr/frontend' }
    defaults:
      run:
        working-directory: ${{ matrix.config.working_directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.config.image_name }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.config.working_directory }}
          file: ${{ matrix.config.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.config.image_name }}:nightly
          labels: ${{ steps.meta.outputs.labels }}
