//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub owner: i32,
	#[sea_orm(column_type = "Text", unique)]
	pub name: String,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
	#[sea_orm(column_type = "Text", nullable, unique)]
	pub iban: Option<String>,
	pub balance: i32,
	pub currency: i32,
	pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::currency::Entity",
		from = "Column::Currency",
		to = "super::currency::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Currency,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::Owner",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User,
	#[sea_orm(has_many = "super::user_account::Entity")]
	UserAccount,
}

impl Related<super::currency::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Currency.def()
	}
}

impl Related<super::user_account::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserAccount.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		super::user_account::Relation::User.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::user_account::Relation::Account.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
