//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0-rc.1

pub mod account;
pub mod budget;
pub mod currency;
pub mod error;
pub mod prelude;
pub mod transaction;
pub mod user;
pub mod user_account;
pub mod utility;
